
# SEO settings
title: "天马行空的"
title2: "景耕" # default: ""
description: "关于技术、生活，略带装B主义色彩的blog"
keywords: "机器学习, 数据挖掘, C++, Python"
url: https://luminarytian.github.io/ # site url
#baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/luminarytian
disqus_shortname: "景耕"
twitter_username: ""
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "景耕"
  job      : "年轻的进程误工人员，目前就职于搜狗"
  bio      : "“总有人会赢，那为什么就不能是我呢？” -- 科比"
  thumb    : assets/images/author.jpg
  email    : luminary.tian@gmail.com
  url      : http://weibo.com/u/2431436281?is_all=1
  github   : https://luminarytian.github.io
  twitter  : 
  facebook : 
  linkedin : 

# social settings
og_locale: "zh_CN"
twitter_card: ""
twitter_site: ""

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
